### ISSUE TITLE
MacOS linker args

### ISSUE THREAD

**Issue by zifeo** [mityax/rustimport#2]
Is it unclear if this library support M1 macs or what is the required config for arm build to succeed?

Related to https://github.com/PyO3/pyo3/issues/1800

**Comment by mityax** [comment]
I haven't worked with M1 myself yet, the architecture is not relevant for rustimport directly though. This project just uses cargo/rustc and optionally pyo3, which afaik support M1 (?).

If you need to supply any additional configuration via e.g. additional command line arguments, there are some ways to do it though - please tell me if so.

**Comment by zifeo** [comment]
@mityax I just tried all combination I could find in the PyO3 repo and only managed to get a stable build using Maturin directly. I assume some runtime injections are used somewhere depending on the platform. Rather sad, rustimport definitely offers a better interface.

**Comment by mityax** [comment]
It seems like maturin is adding some commandline args on macOS autmatically. Could you try [this](https://github.com/PyO3/pyo3/issues/1330#issuecomment-748621681) alternative way of adding them?

If that solves it I might make rustimport add them automatically as well for the sake of simplicity.

**Comment by zifeo** [comment]
@mityax Thanks. I tried again this morning with fresh eyes, and managed to get it compiling using https://pyo3.rs/master/building_and_distribution.html#macos in the project local config `./.cargo/config.toml`. Would it be possible to add pyo3_build_config in rustimport directly to avoid additional config?

**Comment by zifeo** [comment]
Also, you may want to include some [code signing](https://docs.rs/apple-codesign/latest/apple_codesign/) logic (`codesign --verify --verbose --sign - native.cpython-310-darwin.so`) . Currently, it seems that the generated `.so` is rewritten violating its signature when used by another process (you can also remove and recreate the file instead).

**Comment by mityax** [comment]
I added a commit to set the linker args automatically, just as setuptools-rust does. 

I prefer this command-line argument approach since it doesn't require changing any files or adding dependencies and is pretty dynamic (other templates than pyo3 could now also add additional arguments).

Could you try installing the latest version from git to see if it works correctly?
```commandline
$ pip install --force-reinstall --no-cache git+https://github.com/mityax/rustimport.git
```

---

> Also, you may want to include some [code signing](https://docs.rs/apple-codesign/latest/apple_codesign/) logic

Thanks for bringing that up. My guess is that the signature is not valid anymore because of the [appended checksum](https://github.com/mityax/rustimport/blob/master/CONTRIBUTING.md#what-happens-when-we-import-a-rust-module) – would that makes sense? Also, since I'm not an apple dev - what exactly are the benefits of codesigning in this context and does cargo do that automatically by default?

**Comment by zifeo** [comment]
@mityax Works well, thanks.

> My guess is that the signature is not valid anymore because of the [appended checksum](https://github.com/mityax/rustimport/blob/master/CONTRIBUTING.md#what-happens-when-we-import-a-rust-module)

I would assume so. As a temporary workaround, removing the file before re-creating it does the job. I am sadly unfamiliar with the topic. Maybe the a flag to re-create or sign the bundle would do the job?
