### ISSUE TITLE
error: linking with `cc` failed (rustimport 1.2.0)

### ISSUE THREAD

**Issue by fzyzcjy** [mityax/rustimport#7]
It raises: https://gist.github.com/fzyzcjy/4c54279c5078a12546d4f30eb93afbff

**Comment by mityax** [comment]
Could you send me a small reproducible example code?
Also, are you using MacOS or which OS?

**Comment by fzyzcjy** [comment]
macos x86. I will try to make a minimal reproducible later

**Comment by fzyzcjy** [comment]
I am surprised by this though, since that comment should be nothing but a marker...

**Comment by mityax** [comment]
Ah okay, well that explains it. This comment has to be the first non-empty line of the file, otherwise it's not recognized (also stated in the readme).



> I am surprised by this though, since that comment should be nothing but a marker...

Not quite. `// rustimport` would be nothing but a marker, but `// rustimport:pyo3` also causes the pyo3 template to be applied, which is responsible for generating the pyo3 binding code - this explains the weird errors you got, I guess.

**Comment by fzyzcjy** [comment]
I see. hope this restriction can be relaxed, otherwise it may be confusing for new users ;)
