### ISSUE TITLE
share cache for different directories

### ISSUE THREAD

**Issue by fzyzcjy** [mityax/rustimport#8]
Hi thanks for the lib! My use case is like this: I have some python+rust code (say inside folder_a). Then, whenever I need to execute it (each execution takes e.g. several days, because it is deep learning), I will (use a script to) copy folder_a to something like folder_202201040001, and then execute python script there. In other words, each execution will create one new folder.

Then the problem is, rustimport seems not to reuse cache in this case. Instead, for each different folder, it considers it as a brand new thing and re-compile the whole rust code, which is time/cpu/disk consuming. Thus, is it possible to share cache between folders? Thanks

**Comment by mityax** [comment]
Hm, that's a very special usecase. I think one way you should be able to do it would be to have your rust crate/workspace in a shared folder and not copy it over along with the python script. Then, you can add that folder to your `PYTHONPATH`.

This should work because rustimport basically uses the path to your crate as the cache key – where it is imported from does not matter.

**Comment by fzyzcjy** [comment]
> have your rust crate/workspace in a shared folder and not copy it over along with the python script.

well that is not possible: why I *copy* is because I want completely code isolation :/

You know, one deep learning execution can take days (or weeks), so surely the main code can be changed a lot, while I want to ensure the running code is untouched

**Comment by mityax** [comment]
Hm, then I guess you need to implement some hacky solution in your script (the one that copies the other stuff around).

Maybe sth like this (untested, just a draft):
```python3
import shutil
from rustimport.importable import CrateImportable

original_path = "/path/to/your/source/crate/Cargo.toml"
destination_path = "/path/to/the/directory/to/copy/to/Cargo.toml"

original = CrateImportable(original_path, "<fullname>")  # fullname = the name you import the crate under (e.g. `myworkspace.mycrate`)
destination = CrateImportable(destination_path, "<fullname>")

if original.needs_rebuild(release=True):
    original.build(release=True)

old_cache_dir = original.build_tempdir
new_cache_dir = destination.build_tempdir

os.makedirs(new_cache_dir, exists_ok=True)
shutil.copytree(old_cache_dir, new_cache_dir)
```

**Comment by mityax** [comment]
One more thing: If one execution for you only means starting one python process, then changing the code on the disk will not be reflected since python loads the extension only once into memory when it is imported. If however, you're starting and stopping python processes later on, this won't help you of course.

**Comment by mityax** [comment]
Actually I just had one more idea, which might be the cleanest & easiest way to do this.

Whenever you start one execution of your ML app, you first build the current version of your code in the original location, using the cli (`pyhon -m rustimport build --release`) or sth like this:

```python3
from rustimport import build_filepath

i = build_filepath("/path/to/original/rust/crate/Cargo.toml", release=True)
```

Then you copy the just built extension (using `i.extension_path`) and, if you prefer to, also the whole crate directory, to your new location. From there, you only import the pre-built extension you copied over (just import it directly, without even using rustimport).

This way, your build cache will be persisted, since all builds happen in the original directory, but still you have a complete code isolation.

**Comment by fzyzcjy** [comment]
Thanks for the suggestions! I will try them.

> One more thing: If one execution for you only means starting one python process, then changing the code on the disk will not be reflected since python loads the extension only once into memory when it is imported. If however, you're starting and stopping python processes later on, this won't help you of course.

Yes I guess it starts new processes, since it uses `ray` for some kind of distributed scheduling
